apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  securityContext:
    runAsUser: 1000 # Permission at pod level
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: app-config
      securityContext:
        runAsUser: 1000 #Permission at container level
        capabilities:
          add: ["MAC_ADMIN"]
