apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
  labels:
    name: simple-webapp-color
spec:
  containers:
    - name: nginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large
