apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          port: 8080
          path: /api/pd
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 5
